### PR TITLE
updated login endpoint

### PR DESCRIPTION
**Pull request by mikepsinn**

### CODE REVIEW

**Comment by buster92** [comment]
Mike while doing several tests, I just had some errors while syncing data for example,

**Comment by mikepsinn** [comment]
Thanks, @buster92 .  I guess we should resolve the errors first?  Can you create issues for them and paste all relevant information?

**Comment by mikepsinn** [comment]
Do you get these timeout errors when you run the tests on the master or develop branches? @buster92

**Comment by buster92** [comment]
Well they where just timeouts errors when waiting for something that took longer

**Comment by buster92** [comment]
I didn't tryied on develop or master, I will.

**Comment by buster92** [comment]
@mikepsinn I get the same errors, I think is probably because the test account is very old and have many data to load.

**Comment by mikepsinn** [comment]
It shouldn't matter how much data there is to load.  It should always work.  Are you getting a timeout error message from the API or is the response time just greater than the app's timeout limit?  How long is the timeout currently?

**Comment by buster92** [comment]
For example when syncing data, the test wait 50 seconds to check, that one always fails

**Comment by mikepsinn** [comment]
Do you know what the request and parameters are so we can try it in the browser?

Then we can know if it's a problem with the request, the API, or something in the Android app or SDK.

**Pull request merged**
